[package]
name = "lbs"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
rand = "*"
serde = "*"
serde_derive = "*"
bincode = "*"
log = { version = "0.4", features = ["std"] }

[dev-dependencies]
chrono = "0.4"

